// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (workspace_id, user_id, name, key_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, user_id, name, key_hash, created_at, revoked_at
`

type CreateApiKeyParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	KeyHash     string
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.WorkspaceID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, workspace_id, user_id, name, key_hash, created_at, revoked_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, workspace_id, user_id, name, key_hash, created_at, revoked_at FROM api_keys
WHERE workspace_id = $1 AND revoked_at IS NULL
`

func (q *Queries) ListApiKeys(ctx context.Context, workspaceID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeys, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :one
UPDATE api_keys SET revoked_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, user_id, name, key_hash, created_at, revoked_at
`

type RevokeApiKeyParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeApiKey, arg.ID, arg.WorkspaceID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
