// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (workspace_id, created_by, token, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, created_by, token, created_at, expires_at, used_at
`

type CreateInviteParams struct {
	WorkspaceID pgtype.UUID
	CreatedBy   pgtype.UUID
	Token       string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.Token,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, workspace_id, created_by, token, created_at, expires_at, used_at FROM invites
WHERE token = $1
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const useInvite = `-- name: UseInvite :one
UPDATE invites SET used_at = NOW()
WHERE token = $1 AND used_at IS NULL
RETURNING id, workspace_id, created_by, token, created_at, expires_at, used_at
`

func (q *Queries) UseInvite(ctx context.Context, token string) (Invite, error) {
	row := q.db.QueryRow(ctx, useInvite, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
