// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIssuesByProjectFiltered = `-- name: CountIssuesByProjectFiltered :one
SELECT COUNT(*) FROM issues
WHERE project_id = $1
    AND ($2::text  IS NULL OR status   = $2)
    AND ($3::text     IS NULL OR type     = $3)
    AND ($4::uuid     IS NULL OR assignee_id  = $4)
    AND ($5::date      IS NULL OR due_date <= $5)
    AND ($6::date         IS NULL OR due_date >= $6)
`

type CountIssuesByProjectFilteredParams struct {
	ProjectID  pgtype.UUID
	Status     pgtype.Text
	Type       pgtype.Text
	AssigneeID pgtype.UUID
	DueBefore  pgtype.Date
	DueAfter   pgtype.Date
}

func (q *Queries) CountIssuesByProjectFiltered(ctx context.Context, arg CountIssuesByProjectFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuesByProjectFiltered,
		arg.ProjectID,
		arg.Status,
		arg.Type,
		arg.AssigneeID,
		arg.DueBefore,
		arg.DueAfter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuesByWorkspaceFiltered = `-- name: CountIssuesByWorkspaceFiltered :one
SELECT COUNT(*) FROM issues
JOIN projects ON issues.project_id = projects.id
WHERE projects.workspace_id = $1
    AND ($2::uuid IS NULL OR issues.project_id = $2)
    AND ($3::text  IS NULL OR issues.status   = $3)
    AND ($4::text     IS NULL OR issues.type     = $4)
    AND ($5::uuid     IS NULL OR issues.assignee_id  = $5)
    AND ($6::date      IS NULL OR issues.due_date <= $6)
    AND ($7::date         IS NULL OR issues.due_date >= $7)
`

type CountIssuesByWorkspaceFilteredParams struct {
	WorkspaceID     pgtype.UUID
	ProjectIDFilter pgtype.UUID
	Status          pgtype.Text
	Type            pgtype.Text
	AssigneeID      pgtype.UUID
	DueBefore       pgtype.Date
	DueAfter        pgtype.Date
}

func (q *Queries) CountIssuesByWorkspaceFiltered(ctx context.Context, arg CountIssuesByWorkspaceFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuesByWorkspaceFiltered,
		arg.WorkspaceID,
		arg.ProjectIDFilter,
		arg.Status,
		arg.Type,
		arg.AssigneeID,
		arg.DueBefore,
		arg.DueAfter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (project_id, title, overview, type, status, position, assignee_id, created_by, due_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, title, overview, type, status, position, assignee_id, created_by, due_date, created_at, updated_at
`

type CreateIssueParams struct {
	ProjectID  pgtype.UUID
	Title      string
	Overview   pgtype.Text
	Type       string
	Status     string
	Position   float64
	AssigneeID pgtype.UUID
	CreatedBy  pgtype.UUID
	DueDate    pgtype.Date
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.ProjectID,
		arg.Title,
		arg.Overview,
		arg.Type,
		arg.Status,
		arg.Position,
		arg.AssigneeID,
		arg.CreatedBy,
		arg.DueDate,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Overview,
		&i.Type,
		&i.Status,
		&i.Position,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIssue = `-- name: DeleteIssue :exec
DELETE FROM issues
WHERE id = $1 AND project_id = $2
`

type DeleteIssueParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) DeleteIssue(ctx context.Context, arg DeleteIssueParams) error {
	_, err := q.db.Exec(ctx, deleteIssue, arg.ID, arg.ProjectID)
	return err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, project_id, title, overview, type, status, position, assignee_id, created_by, due_date, created_at, updated_at FROM issues
WHERE id = $1 AND project_id = $2
`

type GetIssueByIDParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) GetIssueByID(ctx context.Context, arg GetIssueByIDParams) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByID, arg.ID, arg.ProjectID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Overview,
		&i.Type,
		&i.Status,
		&i.Position,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxPositionByProjectAndStatus = `-- name: GetMaxPositionByProjectAndStatus :one
SELECT COALESCE(MAX(position), 0) FROM issues 
WHERE project_id = $1 AND status = $2
`

type GetMaxPositionByProjectAndStatusParams struct {
	ProjectID pgtype.UUID
	Status    string
}

func (q *Queries) GetMaxPositionByProjectAndStatus(ctx context.Context, arg GetMaxPositionByProjectAndStatusParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxPositionByProjectAndStatus, arg.ProjectID, arg.Status)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listIssuesByProjectFiltered = `-- name: ListIssuesByProjectFiltered :many
SELECT id, project_id, title, overview, type, status, position, assignee_id, created_by, due_date, created_at, updated_at FROM issues
WHERE project_id = $1
    AND ($2::text  IS NULL OR status   = $2)
    AND ($3::text     IS NULL OR type     = $3)
    AND ($4::uuid     IS NULL OR assignee_id  = $4)
    AND ($5::date      IS NULL OR due_date <= $5)
    AND ($6::date         IS NULL OR due_date >= $6)
ORDER BY
    CASE WHEN $7::text = 'title'              AND $8::text = 'asc'       THEN title              END ASC       NULLS LAST,
    CASE WHEN $7::text = 'title'              AND $8::text = 'desc'     THEN title              END DESC     NULLS LAST,
    CASE WHEN $7::text = 'status'          AND $8::text = 'asc'       THEN status          END ASC       NULLS LAST,
    CASE WHEN $7::text = 'status'          AND $8::text = 'desc'     THEN status          END DESC     NULLS LAST,
    CASE WHEN $7::text = 'due_date'     AND $8::text = 'asc'       THEN due_date     END ASC       NULLS LAST,
    CASE WHEN $7::text = 'due_date'     AND $8::text = 'desc'     THEN due_date     END DESC     NULLS LAST,
    CASE WHEN $7::text = 'created_at'   AND $8::text = 'asc'       THEN created_at   END ASC       NULLS LAST,
    CASE WHEN $7::text = 'created_at'   AND $8::text = 'desc'     THEN created_at   END DESC     NULLS LAST,
    position ASC
LIMIT $10 OFFSET $9
`

type ListIssuesByProjectFilteredParams struct {
	ProjectID  pgtype.UUID
	Status     pgtype.Text
	Type       pgtype.Text
	AssigneeID pgtype.UUID
	DueBefore  pgtype.Date
	DueAfter   pgtype.Date
	SortBy     string
	SortOrder  string
	Offset     int32
	Limit      int32
}

func (q *Queries) ListIssuesByProjectFiltered(ctx context.Context, arg ListIssuesByProjectFilteredParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesByProjectFiltered,
		arg.ProjectID,
		arg.Status,
		arg.Type,
		arg.AssigneeID,
		arg.DueBefore,
		arg.DueAfter,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Overview,
			&i.Type,
			&i.Status,
			&i.Position,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByWorkspaceFiltered = `-- name: ListIssuesByWorkspaceFiltered :many
SELECT issues.id, issues.project_id, issues.title, issues.overview, issues.type, issues.status, issues.position, issues.assignee_id, issues.created_by, issues.due_date, issues.created_at, issues.updated_at FROM issues
JOIN projects ON issues.project_id = projects.id
WHERE projects.workspace_id = $1
    AND ($2::uuid IS NULL OR issues.project_id = $2)
    AND ($3::text  IS NULL OR issues.status   = $3)
    AND ($4::text     IS NULL OR issues.type     = $4)
    AND ($5::uuid     IS NULL OR issues.assignee_id  = $5)
    AND ($6::date      IS NULL OR issues.due_date <= $6)
    AND ($7::date         IS NULL OR issues.due_date >= $7)
ORDER BY
    CASE WHEN $8::text = 'title'              AND $9::text = 'asc'       THEN issues.title              END ASC       NULLS LAST,
    CASE WHEN $8::text = 'title'              AND $9::text = 'desc'     THEN issues.title              END DESC     NULLS LAST,
    CASE WHEN $8::text = 'status'          AND $9::text = 'asc'       THEN issues.status          END ASC       NULLS LAST,
    CASE WHEN $8::text = 'status'          AND $9::text = 'desc'     THEN issues.status          END DESC     NULLS LAST,
    CASE WHEN $8::text = 'due_date'     AND $9::text = 'asc'       THEN issues.due_date     END ASC       NULLS LAST,
    CASE WHEN $8::text = 'due_date'     AND $9::text = 'desc'     THEN issues.due_date     END DESC     NULLS LAST,
    CASE WHEN $8::text = 'created_at'   AND $9::text = 'asc'       THEN issues.created_at   END ASC       NULLS LAST,
    CASE WHEN $8::text = 'created_at'   AND $9::text = 'desc'     THEN issues.created_at   END DESC     NULLS LAST,
    position ASC
LIMIT $11 OFFSET $10
`

type ListIssuesByWorkspaceFilteredParams struct {
	WorkspaceID     pgtype.UUID
	ProjectIDFilter pgtype.UUID
	Status          pgtype.Text
	Type            pgtype.Text
	AssigneeID      pgtype.UUID
	DueBefore       pgtype.Date
	DueAfter        pgtype.Date
	SortBy          string
	SortOrder       string
	Offset          int32
	Limit           int32
}

func (q *Queries) ListIssuesByWorkspaceFiltered(ctx context.Context, arg ListIssuesByWorkspaceFilteredParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesByWorkspaceFiltered,
		arg.WorkspaceID,
		arg.ProjectIDFilter,
		arg.Status,
		arg.Type,
		arg.AssigneeID,
		arg.DueBefore,
		arg.DueAfter,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Overview,
			&i.Type,
			&i.Status,
			&i.Position,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssue = `-- name: UpdateIssue :one
UPDATE issues SET
title = $3, 
overview = $4,
type = $5,
status = $6,
position = $7,
assignee_id = $8,
due_date = $9,
updated_at = NOW() 
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, overview, type, status, position, assignee_id, created_by, due_date, created_at, updated_at
`

type UpdateIssueParams struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Title      string
	Overview   pgtype.Text
	Type       string
	Status     string
	Position   float64
	AssigneeID pgtype.UUID
	DueDate    pgtype.Date
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssue,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Overview,
		arg.Type,
		arg.Status,
		arg.Position,
		arg.AssigneeID,
		arg.DueDate,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Overview,
		&i.Type,
		&i.Status,
		&i.Position,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
