// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIssuesByProject = `-- name: CountIssuesByProject :one
SELECT COUNT(*) FROM issues
WHERE project_id = $1
`

func (q *Queries) CountIssuesByProject(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuesByWorkspace = `-- name: CountIssuesByWorkspace :one
SELECT COUNT(*) FROM issues
JOIN projects ON issues.project_id = projects.id
WHERE projects.workspace_id = $1
`

func (q *Queries) CountIssuesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuesByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (project_id, title, overview, type, status, position, assignee_id, created_by, due_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, title, overview, type, status, position, assignee_id, created_by, due_date, created_at, updated_at
`

type CreateIssueParams struct {
	ProjectID  pgtype.UUID
	Title      string
	Overview   pgtype.Text
	Type       string
	Status     string
	Position   float64
	AssigneeID pgtype.UUID
	CreatedBy  pgtype.UUID
	DueDate    pgtype.Date
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.ProjectID,
		arg.Title,
		arg.Overview,
		arg.Type,
		arg.Status,
		arg.Position,
		arg.AssigneeID,
		arg.CreatedBy,
		arg.DueDate,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Overview,
		&i.Type,
		&i.Status,
		&i.Position,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIssue = `-- name: DeleteIssue :exec
DELETE FROM issues
WHERE id = $1 AND project_id = $2
`

type DeleteIssueParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) DeleteIssue(ctx context.Context, arg DeleteIssueParams) error {
	_, err := q.db.Exec(ctx, deleteIssue, arg.ID, arg.ProjectID)
	return err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, project_id, title, overview, type, status, position, assignee_id, created_by, due_date, created_at, updated_at FROM issues
WHERE id = $1 AND project_id = $2
`

type GetIssueByIDParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) GetIssueByID(ctx context.Context, arg GetIssueByIDParams) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByID, arg.ID, arg.ProjectID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Overview,
		&i.Type,
		&i.Status,
		&i.Position,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxPositionByProjectAndStatus = `-- name: GetMaxPositionByProjectAndStatus :one
SELECT COALESCE(MAX(position), 0) FROM issues 
WHERE project_id = $1 AND status = $2
`

type GetMaxPositionByProjectAndStatusParams struct {
	ProjectID pgtype.UUID
	Status    string
}

func (q *Queries) GetMaxPositionByProjectAndStatus(ctx context.Context, arg GetMaxPositionByProjectAndStatusParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxPositionByProjectAndStatus, arg.ProjectID, arg.Status)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listIssuesByProject = `-- name: ListIssuesByProject :many
SELECT id, project_id, title, overview, type, status, position, assignee_id, created_by, due_date, created_at, updated_at FROM issues
WHERE project_id = $1
ORDER BY position ASC 
LIMIT $2 OFFSET $3
`

type ListIssuesByProjectParams struct {
	ProjectID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListIssuesByProject(ctx context.Context, arg ListIssuesByProjectParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Overview,
			&i.Type,
			&i.Status,
			&i.Position,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByWorkspace = `-- name: ListIssuesByWorkspace :many
SELECT issues.id, issues.project_id, issues.title, issues.overview, issues.type, issues.status, issues.position, issues.assignee_id, issues.created_by, issues.due_date, issues.created_at, issues.updated_at FROM issues
JOIN projects ON issues.project_id = projects.id
WHERE projects.workspace_id = $1
ORDER BY issues.position ASC 
LIMIT $2 OFFSET $3
`

type ListIssuesByWorkspaceParams struct {
	WorkspaceID pgtype.UUID
	Limit       int32
	Offset      int32
}

func (q *Queries) ListIssuesByWorkspace(ctx context.Context, arg ListIssuesByWorkspaceParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Overview,
			&i.Type,
			&i.Status,
			&i.Position,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssue = `-- name: UpdateIssue :one
UPDATE issues SET
title = $3, 
overview = $4,
type = $5,
status = $6,
position = $7,
assignee_id = $8,
due_date = $9,
updated_at = NOW() 
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, overview, type, status, position, assignee_id, created_by, due_date, created_at, updated_at
`

type UpdateIssueParams struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Title      string
	Overview   pgtype.Text
	Type       string
	Status     string
	Position   float64
	AssigneeID pgtype.UUID
	DueDate    pgtype.Date
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssue,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Overview,
		arg.Type,
		arg.Status,
		arg.Position,
		arg.AssigneeID,
		arg.DueDate,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Overview,
		&i.Type,
		&i.Status,
		&i.Position,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
