// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	KeyHash     string
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type Invite struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	CreatedBy   pgtype.UUID
	Token       string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	UsedAt      pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash pgtype.Text
	Name         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Workspace struct {
	ID        pgtype.UUID
	Name      string
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	JoinedAt    pgtype.Timestamptz
}
