// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectsByWorkspace = `-- name: CountProjectsByWorkspace :one
SELECT COUNT(*) FROM projects
WHERE workspace_id = $1
`

func (q *Queries) CountProjectsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (workspace_id, name, image_url)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, image_url, created_at, updated_at
`

type CreateProjectParams struct {
	WorkspaceID pgtype.UUID
	Name        string
	ImageUrl    pgtype.Text
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.WorkspaceID, arg.Name, arg.ImageUrl)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1 AND workspace_id = $2
`

type DeleteProjectParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.WorkspaceID)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, workspace_id, name, image_url, created_at, updated_at FROM projects
WHERE id = $1 AND workspace_id = $2
`

type GetProjectByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.WorkspaceID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByWorkspace = `-- name: ListProjectsByWorkspace :many
SELECT id, workspace_id, name, image_url, created_at, updated_at FROM projects
WHERE workspace_id = $1
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type ListProjectsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID
	Limit       int32
	Offset      int32
}

func (q *Queries) ListProjectsByWorkspace(ctx context.Context, arg ListProjectsByWorkspaceParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET 
name = $3, 
image_url = $4,
updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, image_url, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Name        string
	ImageUrl    pgtype.Text
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ImageUrl,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
