// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkspaceStats = `-- name: GetWorkspaceStats :one
SELECT
    (SELECT COUNT(*)
    FROM projects p
    WHERE p.workspace_id = $1)::int AS total_projects,
    (SELECT COUNT(*)
    FROM issues i
    JOIN projects p ON i.project_id = p.id
    WHERE p.workspace_id = $1)::int AS total_issues, 
    (SELECT COUNT(*)
    FROM issues i
    JOIN projects p ON i.project_id = p.id
    WHERE p.workspace_id = $1 AND i.assignee_id = $2)::int AS assigned_issues,
    (SELECT COUNT(*)
    FROM issues i
    JOIN projects p ON i.project_id = p.id
    WHERE p.workspace_id = $1 AND i.status = 'done')::int AS completed_issues,
    (SELECT COUNT(*)
    FROM issues i
    JOIN projects p ON i.project_id = p.id
    WHERE p.workspace_id = $1
        AND i.due_date < CURRENT_DATE
        AND i.status != 'done')::int AS overdue_issues
`

type GetWorkspaceStatsParams struct {
	WorkspaceID pgtype.UUID
	AssigneeID  pgtype.UUID
}

type GetWorkspaceStatsRow struct {
	TotalProjects   int32
	TotalIssues     int32
	AssignedIssues  int32
	CompletedIssues int32
	OverdueIssues   int32
}

func (q *Queries) GetWorkspaceStats(ctx context.Context, arg GetWorkspaceStatsParams) (GetWorkspaceStatsRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceStats, arg.WorkspaceID, arg.AssigneeID)
	var i GetWorkspaceStatsRow
	err := row.Scan(
		&i.TotalProjects,
		&i.TotalIssues,
		&i.AssignedIssues,
		&i.CompletedIssues,
		&i.OverdueIssues,
	)
	return i, err
}
