// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING workspace_id, user_id, role, joined_at
`

type AddMemberParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT workspace_id, user_id, role, joined_at FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT workspace_id, user_id, role, joined_at FROM workspace_members
WHERE workspace_id = $1
`

func (q *Queries) ListMembers(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceMember, error) {
	rows, err := q.db.Query(ctx, listMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceMember
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.WorkspaceID, arg.UserID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE workspace_members SET role = $3
WHERE workspace_id = $1 AND user_id = $2
RETURNING workspace_id, user_id, role, joined_at
`

type UpdateMemberRoleParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
